# Generated by Django 5.0.6 on 2024-07-04 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_JuriGest", "0003_rename_tipo_sentencia_a_quien_aplica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentencia",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
